# Numpy

In [1]:
import numpy as np

In [25]:
myarr = np.array([[11,22,33,44,55,66]])

In [26]:
myarr

array([[11, 22, 33, 44, 55, 66]])

In [27]:
myarr.shape

(1, 6)

In [29]:
myarr.dtype

dtype('int32')

array creation from conversion from other python structures

In [33]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [35]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
listarray.shape

(3, 3)

In [38]:
listarray.dtype

dtype('int32')

In [39]:
listarray.size

9

In [41]:
zeros = np.zeros(((2,5)))

In [42]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
zeros.shape

(2, 5)

In [44]:
zeros.dtype

dtype('float64')

In [45]:
rng = np.arange(15)

In [46]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
matrix = np.identity(5)

In [48]:
matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
matrix.shape

(5, 5)

In [50]:
matrix.dtype

dtype('float64')

In [51]:
arr = np.arange(0,99)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [53]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [55]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [57]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [58]:
arr = np.array(x)

In [59]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
arr.sum(axis=0)

array([12, 15, 18])

In [61]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [62]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [63]:
arr.argmax()

8

In [64]:
arr.argmin()

0

In [65]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [66]:
arr1 = np.array([[1,1,1],[2,2,2],[3,3,3]])

In [67]:
arr2 = np.array([[4,4,4],[5,5,5],[6,6,6]])

In [68]:
arr1

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [69]:
arr2

array([[4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

In [70]:
arr1+arr2

array([[5, 5, 5],
       [7, 7, 7],
       [9, 9, 9]])

In [71]:
arr1

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [72]:
arr2

array([[4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

In [73]:
arr1*arr2

array([[ 4,  4,  4],
       [10, 10, 10],
       [18, 18, 18]])

In [74]:
arr3 = np.array([[9,36,81],[4,16,64],[25,625,100]])

In [75]:
arr3

array([[  9,  36,  81],
       [  4,  16,  64],
       [ 25, 625, 100]])

In [78]:
np.sqrt(arr3)

array([[ 3.,  6.,  9.],
       [ 2.,  4.,  8.],
       [ 5., 25., 10.]])